### ISSUE TITLE
Release 0.2 to Conjars 

### ISSUE THREAD

**Issue by mstump** [pingles/cascading.cassandra#4]
Can you push a new jar to the repo please?  Thanks.

**Comment by pingles** [comment]
Thanks, I've pushed an update- I've migrated it to a new group (cascading.cassandra): http://conjars.org/cascading.cassandra

The profile isn't showing the new group yet, but once it does, if you paste your public key here I'll add it to the group so you can also push releases.

Thanks,
Paul

**Comment by mstump** [comment]
Hey Paul, 

Thanks for doing the push.  I registered with conjars as mstump.  My public key is:

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfk0flIWCug6U0R4ZIjL9F9pd72JWIAJ3wcqJgmg0ANwn32OpBUZYMP67s6/muEl/yO6w3WBpT5Ths4MLQm2A/oho0CWUHr+O0hHVB1q8X0vDEsij2nt6eSglORuaR/+B9vr/UmhddAGSc42gmlwp+2n+KJPPv/yYu0TQe4xA5D0+KfEKkPVyIhZMqI5uuIlIYEBDftlmqtfaYmURw9Sech3ETYAgGrg9NLdXpkA9CGeaTdk7xbNLqoQCuYy7wKne+fy8LCtYLoG3SutmzFj4jN+80DJJkC3FeHo+TkSJ0Y95KVXGS6aRCcISlb87SaM/KHITrSGBT8fMSM9D21V0/ mstump@mine.local
